# Generated by Django 4.2.7 on 2023-12-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySelfApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposition', models.CharField(max_length=200)),
            ],
        ),
    ]
