# Generated by Django 4.2.7 on 2023-12-30 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySelfApp', '0003_rename_proposition_sentence_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sentence',
            name='emotions',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='sentence',
            name='verbs',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
