# Generated by Django 4.2.7 on 2024-01-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySelfApp', '0004_sentence_category_sentence_emotions_sentence_verbs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='action',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sentence',
            name='unaction',
            field=models.IntegerField(default=0),
        ),
    ]
