# Generated by Django 4.2.7 on 2024-01-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySelfApp', '0005_sentence_action_sentence_unaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Words',
        ),
        migrations.RenameField(
            model_name='sentence',
            old_name='category',
            new_name='target',
        ),
        migrations.AddField(
            model_name='sentence',
            name='emotion_boolean',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sentence',
            name='signs',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
