# Generated by Django 4.2.7 on 2024-01-06 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mySelfApp', '0006_delete_words_rename_category_sentence_target_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='emotion_boolean',
            new_name='booleans',
        ),
    ]
