# Generated by Django 4.2.7 on 2024-01-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySelfApp', '0007_rename_emotion_boolean_sentence_booleans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='signs',
            new_name='sign',
        ),
        migrations.AlterField(
            model_name='sentence',
            name='booleans',
            field=models.CharField(default='', max_length=100),
        ),
    ]
