# Generated by Django 4.2.7 on 2024-01-27 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mySelfApp', '0008_rename_signs_sentence_sign_alter_sentence_booleans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='action',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='unaction',
        ),
    ]
