# Generated by Django 4.2.7 on 2024-01-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySelfApp', '0010_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='action',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sentence',
            name='unaction',
            field=models.IntegerField(default=0),
        ),
    ]
